source 'https://gems-mirror.drwholdings.com'
gem 'eventmachine', '1.2.7', git: 'https://github.com/eventmachine/eventmachine.git', tag: 'v1.2.7'
gem 'webrick'
gem 'github-pages', group: :jekyll_plugins
